repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-toml
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
